on:
  push:
    branches:
    - main
    paths:
      - "*"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: process
      run: |
        wget https://github.com/magiclen/markdown2html-converter/releases/latest/download/markdown2html-converter
        wget -O darklua-linux.zip https://gitlab.com/seaofvoices/darklua/uploads/1676420b7bdac9ff4ba261c5edf0ae2c/darklua-0.8.0-linux.zip
        chmod +x ./markdown2html-converter
        unzip -o darklua-linux.zip
        chmod +x ./darklua
        ./markdown2html-converter --no-safe --no-cjk-fonts -f --css-path ./github-markdown.css -t "Infinite Store" ./README.md -o ./index.html
        echo "<!--]=]" >> index.html
        ./darklua process loader.luau loader.min.luau
        cat loader.min.luau >> index.html
        echo "-->" >> index.html
        sed -i '1s/^/--\[\=[/' index.html
        rm loader.min.luau darklua darklua-linux.zip markdown2html-converter

    - uses: peter-evans/create-pull-request@v4
      if: ${{ success() || failure() }}
      with:
        commit-message: Generate Pages from Markdown
        committer: GitHub Actions <actions@github.com>
        title: Generate Pages from Markdown
        branch: generate-pages
        delete-branch: true

  publish:
    needs: convert
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: 780c3708c39b75d4747e8a0ecde4f94a
        projectName: Infinite Store
        directory: .
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
